[tool.poetry]
name = "aramaki"
version = "0.1.0"
description = ""
authors = ["Christian Theune <ct@flyingcircus.io>"]
license = "AGPLv3"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
Flask = "^2.2.2"
SQLAlchemy = "^1.4.44"
attrs = "^22.1.0"
click = "^8.1.3"
alembic = "^1.8.1"
waitress = "^2.1.2"

[tool.poetry.group.dev.dependencies]
pytest = "^7.2.0"
pytest-coverage = "^0.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
aramaki-cli = "aramaki.interfaces.cli:main"
aramaki-server = "aramaki.interfaces.flask:main"

[tool.black]
line-length = 80
target-version = ['py310']

[tool.isort]
profile = "black"
line_length = 80
