from _typeshed import Incomplete
from pyramid.config.actions import action_method as action_method
from pyramid.interfaces import IResourceURL as IResourceURL, IResponse as IResponse, ITraverser as ITraverser
from pyramid.util import takes_one_arg as takes_one_arg

class AdaptersConfiguratorMixin:
    def add_subscriber(self, subscriber, iface: Incomplete | None = None, **predicates): ...
    def add_subscriber_predicate(self, name, factory, weighs_more_than: Incomplete | None = None, weighs_less_than: Incomplete | None = None) -> None: ...
    def add_response_adapter(self, adapter, type_or_iface) -> None: ...
    def add_default_response_adapters(self) -> None: ...
    def add_traverser(self, adapter, iface: Incomplete | None = None) -> None: ...
    def add_resource_url_adapter(self, adapter, resource_iface: Incomplete | None = None) -> None: ...

def eventonly(callee): ...
