from _typeshed import Incomplete
from typing import NamedTuple
from webob.byterange import ContentRange as ContentRange, Range as Range
from webob.compat import PY2 as PY2, text_type as text_type
from webob.datetime_utils import parse_date as parse_date, serialize_date as serialize_date
from webob.util import header_docstring as header_docstring, warn_deprecation as warn_deprecation

CHARSET_RE: Incomplete
SCHEME_RE: Incomplete

def environ_getter(key, default=..., rfc_section: Incomplete | None = None): ...
def environ_decoder(key, default=..., rfc_section: Incomplete | None = None, encattr: Incomplete | None = None): ...
def upath_property(key): ...
def deprecated_property(attr, name, text, version): ...
def header_getter(header, rfc_section): ...
def converter(prop, parse, serialize, convert_name: Incomplete | None = None): ...
def list_header(header, rfc_section): ...
def parse_list(value): ...
def serialize_list(value): ...
def converter_date(prop): ...
def date_header(header, rfc_section): ...
def parse_etag_response(value, strong: bool = False): ...
def serialize_etag_response(value): ...
def serialize_if_range(value): ...
def parse_range(value): ...
def serialize_range(value): ...
def parse_int(value): ...
def parse_int_safe(value): ...
serialize_int = str

def parse_content_range(value): ...
def serialize_content_range(value): ...
def parse_auth_params(params): ...

known_auth_schemes: Incomplete

class _authorization(NamedTuple):
    authtype: Incomplete
    params: Incomplete

def parse_auth(val): ...
def serialize_auth(val): ...
