from _typeshed import Incomplete
from webob.compat import escape as escape, string_types as string_types, text_ as text_, text_type as text_type

def html_escape(s): ...
def header_docstring(header, rfc_section): ...
def warn_deprecation(text, version, stacklevel) -> None: ...

status_reasons: Incomplete
status_generic_reasons: Incomplete

def strings_differ(string1, string2, compare_digest=...): ...
