from _typeshed import Incomplete
from waitress.server import TcpWSGIServer

def get_free_port(): ...
def check_server(host, port, path_info: str = '/', timeout: int = 3, retries: int = 30): ...

class StopableWSGIServer(TcpWSGIServer):
    was_shutdown: bool
    runner: Incomplete
    test_app: Incomplete
    application_url: Incomplete
    def __init__(self, application, *args, **kwargs) -> None: ...
    def wrapper(self, environ, start_response): ...
    def run(self) -> None: ...
    def shutdown(self): ...
    @classmethod
    def create(cls, application, **kwargs): ...
    def wait(self, retries: int = 30): ...
