import webob
from _typeshed import Incomplete
from json import loads as loads
from webtest import forms as forms, utils as utils
from webtest.compat import print_stderr as print_stderr, to_bytes as to_bytes, urlparse as urlparse

class TestResponse(webob.Response):
    request: Incomplete
    parser_features: str
    @property
    def forms(self): ...
    @property
    def form(self): ...
    @property
    def testbody(self): ...
    def follow(self, **kw): ...
    def maybe_follow(self, **kw): ...
    def click(self, description: Incomplete | None = None, linkid: Incomplete | None = None, href: Incomplete | None = None, index: Incomplete | None = None, verbose: bool = False, extra_environ: Incomplete | None = None): ...
    def clickbutton(self, description: Incomplete | None = None, buttonid: Incomplete | None = None, href: Incomplete | None = None, index: Incomplete | None = None, verbose: bool = False): ...
    def goto(self, href, method: str = 'get', **args): ...
    @property
    def normal_body(self): ...
    @property
    def unicode_normal_body(self): ...
    def __contains__(self, s) -> bool: ...
    def mustcontain(self, *strings, **kw) -> None: ...
    def __unicode__(self): ...
    @property
    def html(self): ...
    @property
    def xml(self): ...
    @property
    def lxml(self): ...
    @property
    def json(self): ...
    @property
    def pyquery(self): ...
    def showbrowser(self) -> None: ...
