from _typeshed import Incomplete
from webtest.compat import urlencode as urlencode

class NoDefault: ...

def json_method(method): ...
def stringify(value): ...

entity_pattern: Incomplete

def encode_params(params, content_type): ...
def build_params(url, params): ...
def make_pattern(pat): ...

class _RequestCookieAdapter:
    origin_req_host: Incomplete
    def __init__(self, request) -> None: ...
    def is_unverifiable(self): ...
    @property
    def unverifiable(self): ...
    def get_full_url(self): ...
    @property
    def host(self): ...
    def get_host(self): ...
    get_origin_req_host = get_host
    def add_unredirected_header(self, key, header) -> None: ...
    def has_header(self, key): ...
    def get_type(self): ...
    @property
    def type(self): ...
    def header_items(self): ...

class _ResponseCookieAdapter:
    def __init__(self, response) -> None: ...
    def info(self): ...
    def getheaders(self, header): ...
    def get_all(self, headers, default): ...
