from pyramid.util import is_nonstr_iter as is_nonstr_iter

def url_quote(val, safe: str = ''): ...
def quote_plus(val, safe: str = ''): ...
def urlencode(query, doseq: bool = True, quote_via=...): ...
