from _typeshed import Incomplete
from pyramid.scripting import prepare as prepare
from pyramid.scripts.common import get_config_loader as get_config_loader

def setup_logging(config_uri, global_conf: Incomplete | None = None) -> None: ...
def get_app(config_uri, name: Incomplete | None = None, options: Incomplete | None = None): ...
def get_appsettings(config_uri, name: Incomplete | None = None, options: Incomplete | None = None): ...
def bootstrap(config_uri, request: Incomplete | None = None, options: Incomplete | None = None): ...
