from pyramid.encode import url_quote as url_quote, urlencode as urlencode
from pyramid.interfaces import IResourceURL as IResourceURL, IRoutesMapper as IRoutesMapper, IStaticURLInfo as IStaticURLInfo
from pyramid.path import caller_package as caller_package
from pyramid.threadlocal import get_current_registry as get_current_registry
from pyramid.traversal import PATH_SAFE as PATH_SAFE, PATH_SEGMENT_SAFE as PATH_SEGMENT_SAFE, ResourceURL as ResourceURL, quote_path_segment as quote_path_segment
from pyramid.util import bytes_ as bytes_

QUERY_SAFE: str
ANCHOR_SAFE = QUERY_SAFE

def parse_url_overrides(request, kw): ...

class URLMethodsMixin:
    def route_url(self, route_name, *elements, **kw): ...
    def route_path(self, route_name, *elements, **kw): ...
    def resource_url(self, resource, *elements, **kw): ...
    model_url = resource_url
    def resource_path(self, resource, *elements, **kw): ...
    def static_url(self, path, **kw): ...
    def static_path(self, path, **kw): ...
    def current_route_url(self, *elements, **kw): ...
    def current_route_path(self, *elements, **kw): ...

def route_url(route_name, request, *elements, **kw): ...
def route_path(route_name, request, *elements, **kw): ...
def resource_url(resource, request, *elements, **kw): ...
model_url = resource_url

def static_url(path, request, **kw): ...
def static_path(path, request, **kw): ...
def current_route_url(request, *elements, **kw): ...
def current_route_path(request, *elements, **kw): ...
