"""simplify labels

Revision ID: a01c1b272031
Revises: 5362472a2276
Create Date: 2024-03-17 11:24:05.048918

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "a01c1b272031"
down_revision = "5362472a2276"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_labels", table_name="observation", postgresql_using="gin"
    )
    op.alter_column(
        "observation",
        "labels",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=sa.String(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "observation",
        "labels",
        existing_type=sa.String(),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=False,
    )
    op.create_index(
        "ix_labels",
        "observation",
        ["labels"],
        unique=False,
        postgresql_using="gin",
    )
    # ### end Alembic commands ###
