"""create system table

Revision ID: d50e144e683a
Revises: 
Create Date: 2024-02-02 16:49:39.667043

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "d50e144e683a"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "system",
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("title", sa.Text(), nullable=True),
        sa.Column("primary_instance", sa.UUID(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_system")),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("system")
    # ### end Alembic commands ###
