"""add observations

Revision ID: 5362472a2276
Revises: c9618fad3eb8
Create Date: 2024-03-17 09:33:27.491993

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "5362472a2276"
down_revision = "c9618fad3eb8"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "observation",
        sa.Column("system_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column(
            "labels", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column(
            "data", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["system_id"],
            ["system.id"],
            name=op.f("fk_observation_system_id_system"),
        ),
        sa.PrimaryKeyConstraint(
            "system_id", "name", "labels", name=op.f("pk_observation")
        ),
    )
    op.create_index(
        "ix_labels",
        "observation",
        ["labels"],
        unique=False,
        postgresql_using="gin",
    )
    op.drop_index("idxgin", table_name="test", postgresql_using="gin")
    op.drop_table("test")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "test",
        sa.Column("a", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "b",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
        sa.UniqueConstraint("a", "b", name="test_a_b_key"),
    )
    op.create_index(
        "idxgin", "test", ["b"], unique=False, postgresql_using="gin"
    )
    op.drop_index(
        "ix_labels", table_name="observation", postgresql_using="gin"
    )
    op.drop_table("observation")
    # ### end Alembic commands ###
