"""add subsystems

Revision ID: f342ec229dba
Revises: d50e144e683a
Create Date: 2024-02-04 09:00:59.137909

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "f342ec229dba"
down_revision = "d50e144e683a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "subsystem",
        sa.Column("system_id", sa.Uuid(), nullable=False),
        sa.Column("subsystem_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["subsystem_id"],
            ["system.id"],
            name=op.f("fk_subsystem_subsystem_id_system"),
        ),
        sa.ForeignKeyConstraint(
            ["system_id"],
            ["system.id"],
            name=op.f("fk_subsystem_system_id_system"),
        ),
        sa.PrimaryKeyConstraint(
            "system_id", "subsystem_id", name=op.f("pk_subsystem")
        ),
    )
    op.add_column("system", sa.Column("type_", sa.String(), nullable=False))
    op.alter_column(
        "system", "primary_instance", existing_type=sa.UUID(), nullable=False
    )
    op.alter_column(
        "system",
        "title",
        existing_type=sa.TEXT(),
        type_=sa.String(),
        nullable=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "system",
        "title",
        existing_type=sa.String(),
        type_=sa.TEXT(),
        nullable=True,
    )
    op.alter_column(
        "system", "primary_instance", existing_type=sa.UUID(), nullable=True
    )
    op.drop_column("system", "type_")
    op.drop_table("subsystem")
    # ### end Alembic commands ###
