from ..base import AsyncBase as AsyncBase, AsyncIndirectBase as AsyncIndirectBase
from .utils import delegate_to_executor as delegate_to_executor, proxy_method_directly as proxy_method_directly, proxy_property_directly as proxy_property_directly

class AsyncBufferedIOBase(AsyncBase): ...
class AsyncBufferedReader(AsyncBufferedIOBase): ...
class AsyncFileIO(AsyncBase): ...
class AsyncIndirectBufferedIOBase(AsyncIndirectBase): ...
class AsyncIndirectBufferedReader(AsyncIndirectBufferedIOBase): ...
class AsyncIndirectFileIO(AsyncIndirectBase): ...
