from typing import Any

class Error(Exception): ...

def ZSTD_compress(*args, **kwargs): ...
def ZSTD_external() -> Any: ...
def ZSTD_max_threads_count() -> Any: ...
def ZSTD_threads_count() -> Any: ...
def ZSTD_uncompress(*args, **kwargs): ...
def ZSTD_version() -> Any: ...
def ZSTD_version_number() -> Any: ...
def compress(*args, **kwargs): ...
def decompress(bytes) -> Any: ...
def dumps(*args, **kwargs): ...
def loads(*args, **kwargs): ...
def uncompress(*args, **kwargs): ...
def version() -> Any: ...
