from _typeshed import Incomplete

__all__ = ['determineMetaclass', 'getFrameInfo', 'isClassAdvisor', 'minimalBases']

def getFrameInfo(frame): ...
def isClassAdvisor(ob): ...
def determineMetaclass(bases, explicit_mc: Incomplete | None = None): ...
def minimalBases(classes): ...
