from _typeshed import Incomplete
from pyramid.path import AssetResolver as AssetResolver
from pyramid.scripts.common import get_config_loader as get_config_loader, parse_vars as parse_vars
from pyramid.settings import aslist as aslist

def main(argv=..., quiet: bool = False, original_ignore_files: Incomplete | None = None): ...

class PServeCommand:
    description: str
    default_verbosity: int
    parser: Incomplete
    open_url: Incomplete
    args: Incomplete
    worker_kwargs: Incomplete
    watch_files: Incomplete
    ignore_files: Incomplete
    original_ignore_files: Incomplete
    def __init__(self, argv, quiet: bool = False, original_ignore_files: Incomplete | None = None) -> None: ...
    def out(self, msg) -> None: ...
    def get_config_path(self, loader): ...
    def pserve_file_config(self, loader, global_conf: Incomplete | None = None) -> None: ...
    def guess_server_url(self, loader, server_name, global_conf: Incomplete | None = None): ...
    def run(self): ...

def wsgiref_server_runner(wsgi_app, global_conf, **kw) -> None: ...
def cherrypy_server_runner(app, global_conf: Incomplete | None = None, host: str = '127.0.0.1', port: Incomplete | None = None, ssl_pem: Incomplete | None = None, protocol_version: Incomplete | None = None, numthreads: Incomplete | None = None, server_name: Incomplete | None = None, max: Incomplete | None = None, request_queue_size: Incomplete | None = None, timeout: Incomplete | None = None): ...
