"""introduce system category

Revision ID: b7131fce4f69
Revises: f342ec229dba
Create Date: 2024-02-04 20:02:15.241809

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "b7131fce4f69"
down_revision = "f342ec229dba"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "system_category",
        sa.Column("title", sa.String(), nullable=False),
        sa.Column(
            "id",
            sa.Uuid(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_system_category")),
    )
    op.add_column(
        "system", sa.Column("category_id", sa.Uuid(), nullable=False)
    )
    op.create_foreign_key(
        op.f("fk_system_category_id_system_category"),
        "system",
        "system_category",
        ["category_id"],
        ["id"],
    )
    op.drop_column("system", "type_")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "system",
        sa.Column("type_", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.drop_constraint(
        op.f("fk_system_category_id_system_category"),
        "system",
        type_="foreignkey",
    )
    op.drop_column("system", "category_id")
    op.drop_table("system_category")
    # ### end Alembic commands ###
