"""create instance table

Revision ID: c9618fad3eb8
Revises: b7131fce4f69
Create Date: 2024-02-07 08:52:28.748543

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "c9618fad3eb8"
down_revision = "b7131fce4f69"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "instance",
        sa.Column(
            "id",
            sa.Uuid(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_instance")),
    )
    op.add_column(
        "system", sa.Column("primary_instance_id", sa.Uuid(), nullable=False)
    )
    op.create_foreign_key(
        op.f("fk_system_primary_instance_id_instance"),
        "system",
        "instance",
        ["primary_instance_id"],
        ["id"],
    )
    op.drop_column("system", "primary_instance")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "system",
        sa.Column(
            "primary_instance", sa.UUID(), autoincrement=False, nullable=False
        ),
    )
    op.drop_constraint(
        op.f("fk_system_primary_instance_id_instance"),
        "system",
        type_="foreignkey",
    )
    op.drop_column("system", "primary_instance_id")
    op.drop_table("instance")
    # ### end Alembic commands ###
